module.exports = {
  'POST /ziyue/GroupPortraitFacade/listTagAtConf': {
    success: true,
    resultList: [{
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 393183,
        "coverPercent": 69,
        "createTime": "2019-02-18 17:46:09",
        "creatorId": 1,
        "creatorName": "test",
        "description": "地域标签描述...",
        "dimTableName": "dmn_kkl_area",
        "factColumnName": "province_id",
        "factColumnShow": "province_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 1,
        "logic": "地域标签",
        "onlineStatus": "是",
        "onlineTime": "2019-02-18",
        "tagName": "地区",
        "tagType": 2,
        "tagTypeName": "级联关系型"
      },
      {
        "accuracy": 1,
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-02-28 19:37:36",
        "creatorId": 1,
        "creatorName": "test",
        "description": "性别标签描述",
        "dimTableName": "dmn_kkl_sex",
        "factColumnName": "sex_id",
        "factColumnShow": "sex_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 8,
        "logic": "性别标签",
        "onlineStatus": "是",
        "onlineTime": "2019-02-28",
        "tagName": "性别",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 21,
        "coverNum": 564914,
        "coverPercent": 100,
        "createTime": "2019-03-18 09:55:04",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_bind_phone",
        "factColumnName": "bind_phone_id",
        "factColumnShow": "bind_phone_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 46,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "是否绑定手机",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 25174,
        "coverPercent": 4,
        "createTime": "2019-02-28 20:37:54",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近8周作业参与度",
        "factColumnName": "homework_join_rate",
        "factColumnShow": "homework_join_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 13,
        "logic": "近8周作业参与度",
        "onlineStatus": "是",
        "onlineTime": "2019-02-28",
        "tagName": "近8周作业参与度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 69154,
        "coverPercent": 12,
        "createTime": "2019-03-01 13:46:05",
        "creatorId": 1,
        "creatorName": "test",
        "description": "最近一次做作业至今时间间隔",
        "factColumnName": "last_homework_day",
        "factColumnShow": "last_homework_day",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 21,
        "logic": "最近一次做作业至今时间间隔",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "最近一次做作业至今时间间隔（天）",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 11,
        "coverNum": 48120,
        "coverPercent": 8,
        "createTime": "2019-03-01 13:51:46",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近10份视频作业平均完成度",
        "factColumnName": "lesson_complete_rate",
        "factColumnShow": "lesson_complete_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 22,
        "logic": "近10份视频作业平均完成度",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近10份视频作业平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 12,
        "coverNum": 43833,
        "coverPercent": 8,
        "createTime": "2019-03-01 13:52:56",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近10份试题作业做题平均完成度",
        "factColumnName": "question_complete_rate",
        "factColumnShow": "question_complete_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 23,
        "logic": "近10份试题作业做题平均完成度",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近10份试题作业做题平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 8,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-01 13:55:23",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近7天总时长",
        "factColumnName": "total_dur7",
        "factColumnShow": "total_dur7",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 24,
        "logic": "近7天总时长",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近7天总时长",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 8,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-01 13:56:07",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近7天访问页面次数",
        "factColumnName": "pv_7",
        "factColumnShow": "pv_7",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 25,
        "logic": "近7天访问页面次数",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近7天访问页面次数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 8,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-01 13:56:51",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近30天总时长",
        "factColumnName": "total_dur30",
        "factColumnShow": "total_dur30",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 26,
        "logic": "近30天总时长",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近30天总时长",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 8,
        "coverNum": 57944,
        "coverPercent": 10,
        "createTime": "2019-03-01 13:57:16",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近30天访问平均间隔天数",
        "factColumnName": "avg_visit_day",
        "factColumnShow": "avg_visit_day",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 27,
        "logic": "近30天访问平均间隔天数",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近30天访问平均间隔天数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-01 13:59:37",
        "creatorId": 1,
        "creatorName": "test",
        "description": "最后一次自主看课日期距最近日期间隔",
        "factColumnName": "last_view",
        "factColumnShow": "last_view",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 28,
        "logic": "最后一次自主看课日期距最近日期间隔",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "最后一次自主看课日期距最近日期间隔",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-01 14:00:54",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近30天自主看课时长",
        "factColumnName": "view_dur",
        "factColumnShow": "view_dur",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 29,
        "logic": "近30天自主看课时长",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近30天自主看课时长",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-01 14:01:48",
        "creatorId": 1,
        "creatorName": "test",
        "description": "最后一次自主做题日期据最近日期间隔",
        "factColumnName": "last_question",
        "factColumnShow": "last_question",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 30,
        "logic": "最后一次自主做题日期据最近日期间隔",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "最后一次自主做题日期据最近日期间隔",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 83722,
        "coverPercent": 15,
        "createTime": "2019-03-01 14:03:23",
        "creatorId": 1,
        "creatorName": "test",
        "description": "最后一次听FM日期据最近日期间隔",
        "factColumnName": "last_fm",
        "factColumnShow": "last_fm",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 32,
        "logic": "最后一次听FM日期据最近日期间隔",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "最后一次听FM日期据最近日期间隔",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-01 14:06:47",
        "creatorId": 1,
        "creatorName": "test",
        "description": "近8周听FM时长",
        "factColumnName": "fm_dur",
        "factColumnShow": "fm_dur",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 33,
        "logic": "近8周听FM时长",
        "onlineStatus": "是",
        "onlineTime": "2019-03-01",
        "tagName": "近8周听FM时长",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 09:49:31",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_active_school_more",
        "factColumnName": "active_school_more_id",
        "factColumnShow": "active_school_more_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 43,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "是否属于活跃用户占比较多学校",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 09:53:12",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_anchor_fm_like",
        "factColumnName": "anchor_fm_like_id",
        "factColumnShow": "anchor_fm_like_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 44,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周收听FM最多主播",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 21,
        "coverNum": 0,
        "coverPercent": 0,
        "createTime": "2019-03-18 09:54:18",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_bind_card",
        "factColumnName": "phone",
        "factColumnShow": "bind_card_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 45,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "是否绑卡",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 21,
        "coverNum": 220622,
        "coverPercent": 39,
        "createTime": "2019-03-18 09:58:10",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_card_status",
        "factColumnName": "card_status_id",
        "factColumnShow": "card_status_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 47,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "卡状态",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 21,
        "coverNum": 220622,
        "coverPercent": 39,
        "createTime": "2019-03-18 09:59:34",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_card_type",
        "factColumnName": "card_type_id",
        "factColumnShow": "card_type_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 48,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "卡类型",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 13,
        "coverNum": 28464,
        "coverPercent": 5,
        "createTime": "2019-03-18 10:19:42",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_do_evaluation_homework",
        "factColumnName": "do_evaluation_homework_id",
        "factColumnShow": "do_evaluation_homework_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 51,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有做测评作业",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 26223,
        "coverPercent": 5,
        "createTime": "2019-03-18 10:36:28",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_do_homework_hour",
        "factColumnName": "do_homework_hour_id",
        "factColumnShow": "do_homework_hour_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 52,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周做作业最多时间点",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 11,
        "coverNum": 72846,
        "coverPercent": 13,
        "createTime": "2019-03-18 10:37:42",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_do_lesson_homework",
        "factColumnName": "is_view_name",
        "factColumnShow": "is_view_name",
        "factColumnShowType": "keyword",
        "factColumnType": "keyword",
        "factType": 0,
        "id": 53,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有做视频作业",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 12,
        "coverNum": 72846,
        "coverPercent": 13,
        "createTime": "2019-03-18 10:38:44",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_do_question_homework",
        "factColumnName": "do_question_homework_id",
        "factColumnShow": "do_question_homework_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 54,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有做试题作业",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 10:39:52",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_grade",
        "factColumnName": "grade_id",
        "factColumnShow": "grade_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 55,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "年级",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 75041,
        "coverPercent": 13,
        "createTime": "2019-03-18 10:41:00",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_hour_pre",
        "factColumnName": "hour_pre_id",
        "factColumnShow": "hour_pre_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 56,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周访问时长最长时间段",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 10:43:04",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_identity",
        "factColumnName": "identity_id",
        "factColumnShow": "identity_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 58,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "身份",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 24,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 10:43:49",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_is_evaluation",
        "factColumnName": "is_evaluation_id",
        "factColumnShow": "is_evaluation_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 59,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有自主测评",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 10:44:40",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_is_fm",
        "factColumnName": "is_fm_id",
        "factColumnShow": "is_fm_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 60,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有听FM",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 10:45:18",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_is_question",
        "factColumnName": "is_question_id",
        "factColumnShow": "is_question_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 61,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有自主做题",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 72478,
        "coverPercent": 13,
        "createTime": "2019-03-18 10:46:05",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_is_school_pre",
        "factColumnName": "is_school_pre_id",
        "factColumnShow": "is_school_pre_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 62,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周是否最喜欢在学校访问",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 85054,
        "coverPercent": 15,
        "createTime": "2019-03-18 10:46:43",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_is_view",
        "factColumnName": "is_view_id",
        "factColumnShow": "is_view_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 63,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近半年是否有自主看课",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 10:52:06",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_knowledge_question_like",
        "factColumnName": "knowledge_question_like_id",
        "factColumnShow": "knowledge_question_like_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 65,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主做题最多知识点",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 14,
        "coverNum": 151997,
        "coverPercent": 27,
        "createTime": "2019-03-18 10:52:48",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_knowledge_question_wrong",
        "factColumnName": "view_knowledge_id",
        "factColumnShow": "view_knowledge_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 66,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近30天自主做错次数最多知识点",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 211746,
        "coverPercent": 37,
        "createTime": "2019-03-18 10:53:41",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_last_os",
        "factColumnName": "last_os_id",
        "factColumnShow": "last_os_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 67,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "最近访问终端",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 211746,
        "coverPercent": 37,
        "createTime": "2019-03-18 10:54:26",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_life_cycle",
        "factColumnName": "life_cycle_id",
        "factColumnShow": "life_cycle_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 68,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "生命周期状态",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 75456,
        "coverPercent": 13,
        "createTime": "2019-03-18 10:56:20",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_os_pre",
        "factColumnName": "os_pre_id",
        "factColumnShow": "os_pre_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 69,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "最常近8周访问终端",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 395381,
        "coverPercent": 70,
        "createTime": "2019-03-18 10:57:50",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_school",
        "factColumnName": "school_id",
        "factColumnShow": "school_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 70,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "学校",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:06:02",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_subject_question_like",
        "factColumnName": "subject_view_like_id",
        "factColumnShow": "subject_view_like_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 76,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主做题最多科目",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:07:47",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_subject_question_wrong",
        "factColumnName": "subject_question_wrong_id",
        "factColumnShow": "subject_question_wrong_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 77,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主做题错题最多科目",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:08:40",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_subject_view_like",
        "factColumnName": "subject_question_like_id",
        "factColumnShow": "subject_question_like_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 78,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主看课最多科目",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:10:06",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_teacher_view_like",
        "factColumnName": "teacher_view_like_id",
        "factColumnShow": "teacher_view_like_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 79,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主看课最多老师",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:12:16",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_type_fm_like",
        "factColumnName": "bind_card_id",
        "factColumnShow": "bind_card_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 81,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周收听FM最多类型",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:13:12",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_type_question_like",
        "factColumnName": "type_question_like_id",
        "factColumnShow": "type_question_like_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 82,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主做题最多题型",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 11:15:19",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_view_knowledge",
        "factColumnName": "knowledge_question_wrong_id",
        "factColumnShow": "knowledge_question_wrong_name",
        "factColumnShowType": "text",
        "factColumnType": "long",
        "factType": 0,
        "id": 84,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "最近30天自主看课次数最多知识点",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 75041,
        "coverPercent": 13,
        "createTime": "2019-03-18 11:16:18",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_week_pre",
        "factColumnName": "week_pre_id",
        "factColumnShow": "week_pre_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 85,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "星期（近8周访问时长）",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 16,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 16:41:44",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "question_cnt",
        "factColumnShow": "question_cnt",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 90,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近30天自主做题个数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 16:43:11",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "pv_30",
        "factColumnShow": "pv_30",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 91,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近30天访问页面次数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 20,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 16:45:29",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "dimTableName": "dmn_kkl_teacher_permiss",
        "factColumnName": "teacher_permiss_id",
        "factColumnShow": "teacher_permiss_name",
        "factColumnShowType": "keyword",
        "factColumnType": "long",
        "factType": 0,
        "id": 92,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "是否有教师权限",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 17:03:21",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "fm_done_rate",
        "factColumnShow": "fm_done_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 94,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周听FM平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 24,
        "coverNum": 50362,
        "coverPercent": 9,
        "createTime": "2019-03-18 17:05:59",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "last_evaluation",
        "factColumnShow": "last_evaluation",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 95,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "最后一次自主测评日期据最近日期间",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 21,
        "coverNum": 567566,
        "coverPercent": 100,
        "createTime": "2019-03-18 17:07:03",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "data_completion_rate",
        "factColumnShow": "data_completion_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 96,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "资料完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 4167,
        "coverPercent": 1,
        "createTime": "2019-03-18 17:10:08",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "listen_complete_rate",
        "factColumnShow": "listen_complete_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 97,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近10份听力作业平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 12,
        "coverNum": 110525,
        "coverPercent": 19,
        "createTime": "2019-03-18 17:10:35",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "do_question_cnt",
        "factColumnShow": "do_question_cnt",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 99,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近10份试题作业做题个数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 26,
        "coverNum": 211746,
        "coverPercent": 37,
        "createTime": "2019-03-18 18:53:00",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "diffdate",
        "factColumnShow": "diffdate",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 103,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "最后一次访问日期距当前日期间隔",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 25174,
        "coverPercent": 4,
        "createTime": "2019-03-18 19:22:11",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "homework_cnt",
        "factColumnShow": "homework_cnt",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 108,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周做作业个数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 10,
        "coverNum": 110525,
        "coverPercent": 19,
        "createTime": "2019-03-18 19:22:37",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "homework_complete_rate",
        "factColumnShow": "homework_complete_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 109,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近10份作业平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 24,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 19:23:05",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "evaluation_cnt",
        "factColumnShow": "evaluation_cnt",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 110,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周自主测评个数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 18,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 19:46:56",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "fm_cnt",
        "factColumnShow": "fm_cnt",
        "factColumnShowType": "long",
        "factColumnType": "long",
        "factType": 0,
        "id": 111,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近8周听FM个数",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 15,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-18 19:48:32",
        "creatorId": 123456,
        "creatorName": "陈杰",
        "description": "",
        "factColumnName": "view_done_rate",
        "factColumnShow": "view_done_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 112,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-18",
        "tagName": "近30天自主看课平均完成度",
        "tagType": 7,
        "tagTypeName": "不可枚举数值型"
      },
      {
        "bisType": 0,
        "categoryId": 25,
        "coverNum": 152049,
        "coverPercent": 27,
        "createTime": "2019-03-22 17:09:44",
        "creatorId": 3524758551354408965,
        "creatorName": "施鹏飞",
        "description": "",
        "dimTableName": "dmn_kkl_cartoon",
        "factColumnName": "question_right_rate",
        "factColumnShow": "question_right_rate",
        "factColumnShowType": "double",
        "factColumnType": "double",
        "factType": 0,
        "id": 137,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-22",
        "tagName": "沈杰标签",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      },
      {
        "bisType": 0,
        "categoryId": 29,
        "createTime": "2019-03-25 14:00:26",
        "creatorId": 3524758551354408965,
        "creatorName": "施鹏飞",
        "description": "",
        "dimTableName": "dmn_kkl_chapter_section_knowledge",
        "factColumnName": "type_fm_like_name",
        "factColumnShow": "type_fm_like_name",
        "factColumnShowType": "keyword",
        "factColumnType": "keyword",
        "factType": 0,
        "id": 141,
        "logic": "",
        "onlineStatus": "是",
        "onlineTime": "2019-03-25",
        "tagName": "测试标签",
        "tagType": 1,
        "tagTypeName": "可枚举文本型"
      }
    ]
  }
}
